[unix_http_server]
file=/tmp/snacktensors_supervisor.sock

[supervisord]
logfile=/tmp/snacktensors_supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/snacktensors_supervisord.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/snacktensors_supervisor.sock

[program:snacktensors_storage_server]
command=python -m snacktensors.storage_server --host %(ENV_SNACKTENSORS_HOST)s --port %(ENV_SNACKTENSORS_PORT)s --storage-path "%(ENV_SNACKTENSORS_STORAGE_PATH)s" --num-thread %(ENV_SNACKTENSORS_NUM_THREADS)s --chunk-size %(ENV_SNACKTENSORS_CHUNK_SIZE)s --mem-pool-size %(ENV_SNACKTENSORS_MEM_POOL_SIZE)s
directory=%(here)s/..
environment=PYTHONPATH="%(here)s/.."
autostart=false
autorestart=true
startsecs=3
startretries=3
stopwaitsecs=10
stdout_logfile=/tmp/snacktensors_storage_server.log
stderr_logfile=/tmp/snacktensors_storage_server_error.log
user=%(ENV_USER)s